schema_version = "1.0.0"
id = "mocap_pipeline"
version = "1.0.0"
name = "Mocap Pipeline"
tagline = "Automates the Tarena character pipeline"
maintainer = "Pipeline Tool"
type = "add-on"
blender_version_min = "4.2.0"
license = ["SPDX:GPL-2.0-or-later"]
